services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./database:/app/database
      - ./models:/app/models
      - ./reports:/app/reports
    command: streamlit run app/app.py --server.address=0.0.0.0 --server.port=8501

