"""Executive reporting outputs from pipeline artifacts."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd

from src.utils import read_json


def generate_executive_report(config: dict[str, Any]) -> dict[str, Path]:
    """Generate Markdown and HTML executive summaries from latest outputs."""
    output_dir = Path(config["paths"]["output_data"])
    report_dir = Path(config["paths"]["reports"])
    model_dir = Path(config["paths"]["models"])
    report_dir.mkdir(parents=True, exist_ok=True)

    kpi = pd.read_csv(output_dir / "executive_kpi_summary.csv").iloc[0]
    supplier = pd.read_csv(output_dir / "supplier_scorecard.csv").sort_values("supplier_risk_score", ascending=False).head(5)
    carrier = pd.read_csv(output_dir / "carrier_performance_scorecard.csv").sort_values("carrier_reliability_score").head(5)
    routes = pd.read_csv(output_dir / "route_performance_summary.csv").sort_values("total_shipping_cost", ascending=False).head(5)
    inv = pd.read_csv(output_dir / "inventory_recommendations.csv").sort_values("estimated_stockout_risk", ascending=False).head(8)
    forecast_metrics = read_json(model_dir / "forecast_metrics.json")
    model_metrics = read_json(model_dir / "late_delivery_metrics.json")
    opt = pd.read_csv(output_dir / "shipment_allocation_optimization_summary.csv").iloc[0]
    quality = pd.read_csv(output_dir / "data_quality_summary.csv").iloc[0]

    md = f"""# Executive Summary Report

## Reporting Period
{kpi['report_start_date']} to {kpi['report_end_date']}

## Key Performance Indicators
- Shipments analyzed: {int(kpi['total_shipments']):,}
- On-time delivery rate: {kpi['on_time_delivery_rate']:.1%}
- Average delay days: {kpi['average_delay_days']:.2f}
- Total logistics cost: ${kpi['total_logistics_cost']:,.0f}
- Estimated delay cost: ${kpi['estimated_delay_cost']:,.0f}
- Stockout rate: {kpi['stockout_rate']:.1%}

## Major Operational Risks
- Lowest-performing suppliers: {', '.join(supplier['supplier_id'].astype(str).tolist())}
- Lowest-performing carriers: {', '.join(carrier['carrier'].astype(str).tolist())}
- Highest-cost routes: {', '.join(routes['route_id'].astype(str).tolist())}
- Products and warehouses at high stockout risk: {len(inv)}

## Model and Forecasting Summary
- Selected late-delivery model: {model_metrics['selected_model']}
- Test ROC AUC: {model_metrics['test']['roc_auc']:.3f}
- Test recall: {model_metrics['test']['recall']:.3f}
- Forecast weighted MAPE: {forecast_metrics['hist_gradient_boosting']['wmape']:.3f}

## Optimization Recommendations
- Current allocation cost: ${opt['current_allocation_cost']:,.0f}
- Optimized allocation cost: ${opt['optimized_allocation_cost']:,.0f}
- Estimated allocation savings: ${opt['estimated_savings']:,.0f}
- Expected optimized on-time rate: {opt['expected_on_time_rate_optimized']:.1%}

## Data Quality Status
- Records processed: {int(quality['total_records_processed']):,}
- Records rejected: {int(quality['records_rejected']):,}
- Records corrected: {int(quality['records_corrected']):,}
- Final valid shipment records: {int(quality['final_valid_record_count']):,}

## Financial Opportunity
The largest quantified opportunities are delay reduction, inventory policy tuning, and carrier-mode allocation. These estimates are directional because the data is synthetic, but every figure in this report is generated by the pipeline.
"""
    md_path = report_dir / "executive_summary.md"
    html_path = report_dir / "executive_summary.html"
    md_path.write_text(md, encoding="utf-8")
    html = "<html><head><meta charset='utf-8'><title>Executive Summary</title><style>body{font-family:Arial,sans-serif;margin:32px;max-width:980px;line-height:1.5;} code{background:#f4f4f4;padding:2px 4px;}</style></head><body>"
    html += md.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br>\n")
    html += "</body></html>"
    html_path.write_text(html, encoding="utf-8")
    return {"markdown": md_path, "html": html_path}

